## Import Libs

In [1]:
import os
import numpy as np

from model import *
from activation import *
from utils import *

## Load Data

In [2]:
train_path = os.path.join("data", "train.jsonl")
test_path = os.path.join("data","test.jsonl")

In [3]:
X_train, X_test, y_train, y_test= fetch_data(train_path, test_path)

## Data Preprocessing

In [4]:
y_train[0]

array([1, 1, 1, 0, 1, 1, 1, 0, 1])

In [5]:
print(X_train[0])
one_hot_encode(X_train[0])

[1, 4, 3, 1, 4, 4, 3, 1, 4]


array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [6]:
X_train_ho = into_ho(X_train)
X_test_ho = into_ho(X_test)

In [7]:
print("Train Size:",len(X_train_ho))
print("Test Size:", len(X_test_ho))

Train Size: 14041
Test Size: 3453


## Model Training

In [8]:
model = SingleRecurrentPerceptron(lr=0.02, momentum=0.7)

In [9]:
history = model.train(X_train_ho, y_train, epochs=25)

epoch: 1, training loss : 263.95, training accuracy: 49.80%, validation loss: 263.94, validation accuracy: 49.82%
epoch: 2, training loss : 253.51, training accuracy: 48.15%, validation loss: 253.50, validation accuracy: 48.17%
epoch: 3, training loss : 242.29, training accuracy: 52.40%, validation loss: 242.29, validation accuracy: 52.35%
epoch: 4, training loss : 232.09, training accuracy: 59.13%, validation loss: 232.09, validation accuracy: 59.13%
epoch: 5, training loss : 223.22, training accuracy: 61.71%, validation loss: 223.22, validation accuracy: 61.70%
epoch: 6, training loss : 215.61, training accuracy: 62.62%, validation loss: 215.61, validation accuracy: 62.62%
epoch: 7, training loss : 209.11, training accuracy: 62.62%, validation loss: 209.11, validation accuracy: 62.62%
epoch: 8, training loss : 203.52, training accuracy: 62.62%, validation loss: 203.52, validation accuracy: 62.62%
epoch: 9, training loss : 198.70, training accuracy: 62.62%, validation loss: 198.70, va

In [10]:
model.zero_grad()

In [11]:
delta_loss, delta_accuracy = model.calculate_loss(X_test_ho, y_test)

In [13]:
print("Test Accuracy:", delta_accuracy)

Test Accuracy: 0.6210068109590023


3.3149068605476644

In [16]:
model.save(path=f"models/recurrent_perceptron{int(history['val_accuracy'][-1]*100/5)}.pkl")

In [17]:
model.weights

array([ 1.49273762,  0.9008349 , -0.03110481,  0.88635408,  1.57181239,
       -0.14573972,  1.82537535,  0.50062787,  1.98839203,  1.02825094])

## Inference

In [7]:
model = SingleRecurrentPerceptron()
model = model.load("models/recurrent_perceptron_80%.pkl")

## Testing Model