## Import Libs

In [1]:
import os
import numpy as np

from model import *
from activation import *
from utils import *

## Load Data

In [2]:
train_path = os.path.join("data", "train.jsonl")
test_path = os.path.join("data","test.jsonl")

In [3]:
X_train, X_test, y_train, y_test= fetch_data(train_path, test_path)

## Data Preprocessing

In [4]:
y_train[0]

array([1, 1, 1, 0, 1, 1, 1, 0, 1])

In [5]:
print(X_train[0])
one_hot_encode(X_train[0])

[1, 4, 3, 1, 4, 4, 3, 1, 4]


array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [6]:
X_train_ho = into_ho(X_train)
X_test_ho = into_ho(X_test)

In [7]:
print("Train Size:",len(X_train_ho))
print("Test Size:", len(X_test_ho))

Train Size: 14041
Test Size: 3453


## Model Training

In [8]:
model = SingleRecurrentPerceptron(lr=0.1, momentum=0.4, anneal_momentum=0.89)

In [9]:
history = model.train(X_train_ho, y_train, epochs=10)

epoch: 1, training loss : 238.98, training accuracy: 61.62%, validation loss: 238.97, validation accuracy: 61.48%
epoch: 2, training loss : 213.53, training accuracy: 72.10%, validation loss: 213.52, validation accuracy: 72.08%
epoch: 3, training loss : 194.50, training accuracy: 72.37%, validation loss: 194.49, validation accuracy: 72.38%
epoch: 4, training loss : 179.98, training accuracy: 72.56%, validation loss: 179.98, validation accuracy: 72.56%
epoch: 5, training loss : 167.84, training accuracy: 72.88%, validation loss: 167.84, validation accuracy: 72.88%
epoch: 6, training loss : 157.16, training accuracy: 75.28%, validation loss: 157.16, validation accuracy: 75.27%
epoch: 7, training loss : 148.08, training accuracy: 75.78%, validation loss: 148.09, validation accuracy: 75.78%
epoch: 8, training loss : 141.46, training accuracy: 76.42%, validation loss: 141.47, validation accuracy: 76.42%
epoch: 9, training loss : 137.89, training accuracy: 76.42%, validation loss: 137.89, va

In [10]:
delta_loss, delta_accuracy = model.calculate_loss(X_test_ho, y_test)

In [11]:
print("Test Accuracy:", delta_accuracy)

Test Accuracy: 0.727723551955055


In [12]:
model.save(path=f"models/recurrent_perceptron_{int(history['val_accuracy'][-1])}%.pkl")

In [13]:
model.weights

array([ 2.18255245, -0.10987621, -1.18175038, -1.3169876 ,  1.22208694,
        0.04656477,  2.06731215,  0.35541647,  2.56379187,  0.20660407])

## Inference

In [15]:
model = SingleRecurrentPerceptron()
model = model.load("models/recurrent_perceptron_80%.pkl")

In [16]:
delta_loss, delta_accuracy = model.calculate_loss(X_test_ho, y_test)

In [17]:
print("Test Accuracy:", delta_accuracy)

Test Accuracy: 0.7651432230730281


In [18]:
!python app.py

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://eafe155d9fb38b770e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
[1, 4, 3, 1, 4, 4, 3, 1, 4]
^C
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://eafe155d9fb38b770e.gradio.live


## Testing Model