## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from faker import Faker
import random
np.random.seed()
import warnings
warnings.filterwarnings("ignore")

/tmp/ipykernel_87113/2556754689.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
from model import *
from utils import *

## Create Dataset

In [3]:
x = []
palindromes = []
for i in range(1024):
    binary_string = format(i, '010b')
    x.append(binary_string)
    if binary_string == binary_string[::-1]:
        palindromes.append(binary_string)
x = np.array(x)
palindromes = np.array(palindromes)


In [4]:
print(len(palindromes))
palindromes

32


array(['0000000000', '0000110000', '0001001000', '0001111000',
       '0010000100', '0010110100', '0011001100', '0011111100',
       '0100000010', '0100110010', '0101001010', '0101111010',
       '0110000110', '0110110110', '0111001110', '0111111110',
       '1000000001', '1000110001', '1001001001', '1001111001',
       '1010000101', '1010110101', '1011001101', '1011111101',
       '1100000011', '1100110011', '1101001011', '1101111011',
       '1110000111', '1110110111', '1111001111', '1111111111'],
      dtype='<U10')

In [5]:
np.random.shuffle(palindromes)
print(len(palindromes))
palindromes

32


array(['0111111110', '1011001101', '0001111000', '0111001110',
       '0100110010', '1011111101', '1101001011', '1110000111',
       '1000000001', '1110110111', '0101001010', '1001001001',
       '1000110001', '0001001000', '1100110011', '0000110000',
       '1010000101', '1001111001', '1010110101', '1111111111',
       '0110000110', '0010110100', '0110110110', '0011111100',
       '0000000000', '0010000100', '1101111011', '0100000010',
       '1111001111', '0011001100', '0101111010', '1100000011'],
      dtype='<U10')

In [6]:
for i in range(5):
    x = np.concatenate((x, palindromes))
print(len(x))

1184


In [7]:
y = []
for binary_string in x:
    y.append(binary_string == binary_string[::-1])
y = np.array(y)
permutation_index = np.random.permutation(len(x))
x = x[permutation_index]
y = y[permutation_index]

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-1 * x))

def relu(x):
    return np.maximum(0, x)

In [9]:
# a = np.array([1, 2, -3])
# b = np.array([2, 3, 4])
# a*b

In [10]:
LEARNING_RATE = 1e-3
NUM_EPOCHS = 10000

input_size = 10
hidden_layer_size = 20
output_size = 1

weights_ih = np.random.rand(input_size, hidden_layer_size)
weights_ho = np.random.rand(hidden_layer_size, output_size)

In [11]:
x = np.array([])

In [12]:
# LEARNING_RATE = 1e-7
for epoch in range(NUM_EPOCHS):
    tot_loss = 0
    for i, s in enumerate(x):
        inp = np.reshape(np.array([int(char) for char in s]), (1, input_size))
        hlayer_logits = np.dot(inp, weights_ih)
        hlayer_output = sigmoid(hlayer_logits)

        final_logits = np.dot(hlayer_output, weights_ho)
        final_output = sigmoid(final_logits)

        tot_loss += abs(final_output - y[i])

        output_delta = (y[i] - final_output) * final_output * (1 - final_output)

        weights_ho += LEARNING_RATE * hlayer_output.T.dot(output_delta)
        weights_ih += LEARNING_RATE * inp.T.dot(output_delta.dot(weights_ho.T) * hlayer_output * (1 - hlayer_output))

    if epoch % 100 == 0:
        print(f'Epoch {epoch} : loss {tot_loss}')

Epoch 0 : loss 0
Epoch 100 : loss 0
Epoch 200 : loss 0
Epoch 300 : loss 0
Epoch 400 : loss 0
Epoch 500 : loss 0
Epoch 600 : loss 0
Epoch 700 : loss 0
Epoch 800 : loss 0
Epoch 900 : loss 0
Epoch 1000 : loss 0
Epoch 1100 : loss 0
Epoch 1200 : loss 0
Epoch 1300 : loss 0
Epoch 1400 : loss 0
Epoch 1500 : loss 0
Epoch 1600 : loss 0
Epoch 1700 : loss 0
Epoch 1800 : loss 0
Epoch 1900 : loss 0
Epoch 2000 : loss 0
Epoch 2100 : loss 0
Epoch 2200 : loss 0
Epoch 2300 : loss 0
Epoch 2400 : loss 0
Epoch 2500 : loss 0
Epoch 2600 : loss 0
Epoch 2700 : loss 0
Epoch 2800 : loss 0
Epoch 2900 : loss 0
Epoch 3000 : loss 0
Epoch 3100 : loss 0
Epoch 3200 : loss 0
Epoch 3300 : loss 0
Epoch 3400 : loss 0
Epoch 3500 : loss 0
Epoch 3600 : loss 0
Epoch 3700 : loss 0
Epoch 3800 : loss 0
Epoch 3900 : loss 0
Epoch 4000 : loss 0
Epoch 4100 : loss 0
Epoch 4200 : loss 0
Epoch 4300 : loss 0
Epoch 4400 : loss 0
Epoch 4500 : loss 0
Epoch 4600 : loss 0
Epoch 4700 : loss 0
Epoch 4800 : loss 0
Epoch 4900 : loss 0
Epoch 5000 :

In [13]:
LEARNING_RATE = 1e-1
for epoch in range(NUM_EPOCHS):
    tot_loss = 0
    for i, s in enumerate(x):
        inp = np.reshape(np.array([int(char) for char in s]), (1, input_size))
        hlayer_logits = np.dot(inp, weights_ih)
        hlayer_output = sigmoid(hlayer_logits)

        final_logits = np.dot(hlayer_output, weights_ho)
        final_output = sigmoid(final_logits)

        tot_loss += abs(final_output - y[i])

        output_delta = (y[i] - final_output) * final_output * (1 - final_output)

        weights_ho += LEARNING_RATE * hlayer_output.T.dot(output_delta)
        weights_ih += LEARNING_RATE * inp.T.dot(output_delta.dot(weights_ho.T) * hlayer_output * (1 - hlayer_output))

    if epoch % 100 == 0:
        print(f'Epoch {epoch} : loss {tot_loss}')

Epoch 0 : loss 0
Epoch 100 : loss 0
Epoch 200 : loss 0
Epoch 300 : loss 0
Epoch 400 : loss 0
Epoch 500 : loss 0
Epoch 600 : loss 0
Epoch 700 : loss 0
Epoch 800 : loss 0
Epoch 900 : loss 0
Epoch 1000 : loss 0
Epoch 1100 : loss 0
Epoch 1200 : loss 0
Epoch 1300 : loss 0
Epoch 1400 : loss 0
Epoch 1500 : loss 0
Epoch 1600 : loss 0
Epoch 1700 : loss 0
Epoch 1800 : loss 0
Epoch 1900 : loss 0
Epoch 2000 : loss 0
Epoch 2100 : loss 0
Epoch 2200 : loss 0
Epoch 2300 : loss 0
Epoch 2400 : loss 0
Epoch 2500 : loss 0
Epoch 2600 : loss 0
Epoch 2700 : loss 0
Epoch 2800 : loss 0
Epoch 2900 : loss 0
Epoch 3000 : loss 0
Epoch 3100 : loss 0
Epoch 3200 : loss 0
Epoch 3300 : loss 0
Epoch 3400 : loss 0
Epoch 3500 : loss 0
Epoch 3600 : loss 0
Epoch 3700 : loss 0
Epoch 3800 : loss 0
Epoch 3900 : loss 0
Epoch 4000 : loss 0
Epoch 4100 : loss 0
Epoch 4200 : loss 0
Epoch 4300 : loss 0
Epoch 4400 : loss 0
Epoch 4500 : loss 0
Epoch 4600 : loss 0
Epoch 4700 : loss 0
Epoch 4800 : loss 0
Epoch 4900 : loss 0
Epoch 5000 :

In [14]:
x_test1 = '1100110011'
x_test2 = '1100110000'
def test(x):
    inp = np.reshape(np.array([int(char) for char in x]), (1, input_size))
    return sigmoid(np.dot(sigmoid(np.dot(inp, weights_ih)), weights_ho))

print(test(x_test1))
print(test(x_test2))

[[0.99986682]]
[[0.99969992]]


In [ ]:
# np.save('weights_ih.npy', weights_ih)
# np.save('weights_ho.npy', weights_ho)

## New implementation

In [3]:
from utils import activation, dataset, losses
from model import *
import numpy as np

Dataset = dataset.Palindrome_Dataset(n_bits=10)
x_train,y_train = Dataset.get_data(shuffle=True, biasing_factor=20)


In [4]:
model = Palindrome_Model(input_size=10, output_size=1,hidden_layer_sizes=[4],activation='sigmoid')
model.layers

[{'name': 'layer-1',
  'weights': array([[ 0.16769564,  0.75670325,  0.62263716,  0.2727314 ],
         [-0.21284762, -0.18264564,  1.06783169, -0.02231364],
         [ 0.3576575 , -0.10566537,  0.1255692 ,  0.12361673],
         [ 0.98624143, -0.05819921,  0.44425349, -0.11024212],
         [-0.3669962 ,  0.03603563, -0.00349523,  0.08239108],
         [-0.79323559,  0.46767248, -0.00516988, -0.77978055],
         [ 0.61716754, -0.17580501, -0.19064652,  0.01236308],
         [-1.3529401 ,  0.79269499, -0.47349823,  0.07774432],
         [-0.80749843, -0.65498371, -0.58704537, -0.13027883],
         [ 0.19642577, -0.00698707, -0.5577965 ,  0.08915547]]),
  'biases': array([ 2.12912468, -0.76292663, -0.32806309,  0.45187915]),
  'activation': 'relu'},
 {'name': 'layer-2',
  'weights': array([[-1.08293061],
         [-0.23996413],
         [-0.44935948],
         [-0.6134314 ]]),
  'biases': array([0.31689972]),
  'activation': 'sigmoid'}]

In [5]:
model.set_optimizer(lr=0.05,loss="mse", optimizer="bgd")


In [8]:
accuracies, losses = model.train(x_train,y_train,epochs=100,batch_size=16)

Epoch 1/100: 1664sample [00:00, 7016.86sample/s, accuracy=59.6, loss=12.6]
Epoch 2/100: 1664sample [00:00, 8511.71sample/s, accuracy=59.6, loss=12.6] 
Epoch 3/100: 1664sample [00:00, 7746.94sample/s, accuracy=59.6, loss=12.6]
Epoch 4/100: 1664sample [00:00, 7559.14sample/s, accuracy=59.6, loss=12.6]
Epoch 5/100: 1664sample [00:00, 7449.51sample/s, accuracy=59.6, loss=12.6]
Epoch 6/100: 1664sample [00:00, 6748.77sample/s, accuracy=59.6, loss=12.6]
Epoch 7/100: 1664sample [00:00, 7851.24sample/s, accuracy=59.6, loss=12.6]
Epoch 8/100: 1664sample [00:00, 7956.55sample/s, accuracy=59.6, loss=12.6]
Epoch 9/100: 1664sample [00:00, 8060.25sample/s, accuracy=59.6, loss=12.6]
Epoch 10/100: 1664sample [00:00, 7962.99sample/s, accuracy=59.6, loss=12.6]
Epoch 11/100: 1664sample [00:00, 7919.22sample/s, accuracy=59.6, loss=12.6]
Epoch 12/100: 1664sample [00:00, 8106.63sample/s, accuracy=59.6, loss=12.6]
Epoch 13/100: 1664sample [00:00, 8147.39sample/s, accuracy=59.6, loss=12.6]
Epoch 14/100: 1664sa

KeyboardInterrupt: 

In [20]:
y_pred = model(x)
y_pred = np.clip(y_pred, 1e-12, 1 - 1e-12)
-np.sum(y * np.log(y_pred) + (1 - y) * np.log(1 - (y_pred)))

2725399.477086875

In [ ]:
# temp_x = x[:48]
# temp_y = y[:48]
# print(temp_x, temp_y)

#### Resolving Bug

In [1]:
from utils import dataset
from model import Palindrome_Model
import numpy as np
np.random.seed(7)

Dataset = dataset.Palindrome_Dataset(n_bits=10)
x,y = Dataset.get_data(shuffle=True, biasing_factor=20)
model = Palindrome_Model(input_size=10, output_size=1,hidden_layer_sizes=[4],activation='sigmoid')
model.set_optimizer(lr=0.005,loss="bce", optimizer="sgd")

In [2]:
temp = [np.array([1,0,1,1,1,1,1,1,0,1]), np.array([1,1,1,1,1,1,1,1,0,1])]
y_temp = [1, 0]


for x,y in zip(temp,y_temp):
    print(x,y)

[1 0 1 1 1 1 1 1 0 1] 1
[1 1 1 1 1 1 1 1 0 1] 0


In [28]:
model.forward(temp)

array([[0.88834677],
       [0.89637692]])

In [38]:
model.backward([temp[1]], [y_temp[1]])

In [39]:
model.weight_gradients

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0.],
        [0.],
        [0.],
        [0.]])]

In [40]:
model.bias_gradients

[array([0., 0., 0., 0.]), array([0.89496408])]

In [ ]:
x_palindromes = np.array([np.reshape(np.array([int(char) for char in s]), (10,)) for s in Dataset.palindromes])
y_palindromes = np.array([1]*32)

x_non_palindrome = np.array([np.reshape(np.array([int(char) for char in s]), (10,)) for s in Dataset.non_palindromes])
y_non_palindrome = np.array([0]*len(x_non_palindrome))
temp_x = np.concatenate((temp_x,x_palindromes))
temp_y = np.concatenate((temp_y, y_palindromes))
accuracies, losses = model.train(x_palindromes,y_palindromes,epochs=10)

In [ ]:
model.set_optimizer(lr=0.005,loss="mse")
accuracies, losses = model.train(temp_x,temp_y,epochs=100)

In [ ]:
predictions = model.predict(x_palindromes)
accuracy_metric(predictions, y_palindromes)


In [ ]:
predictions = model.predict(x_non_palindrome)
# print(predictions)
accuracy_metric(predictions, y_non_palindrome)

### Batch  Optimization

In [4]:
model.layers

[{'name': 'layer-1',
  'weights': array([[ 0.93264673,  0.97459294, -0.12848894,  0.58921758],
         [-0.61967231, -0.26271703, -0.26330762, -0.93215773],
         [ 0.19383003, -1.06437594,  0.40447317, -0.24151142],
         [-0.44076791, -0.58080072, -0.21027712, -0.61963486],
         [-0.21196891, -0.25251799, -0.36971576, -0.07134193],
         [-0.01738654,  0.49040936, -0.42500098, -0.1270861 ],
         [-0.82970687,  0.77321702,  0.29156391, -0.54454293],
         [ 0.42967041, -0.02238592, -0.17803028,  0.43492721],
         [ 0.39676217, -0.09361975,  0.69012828,  0.31874703],
         [ 0.4822464 ,  0.3571908 ,  0.47563312,  0.07272139]]),
  'biases': array([-0.73642481, -0.58666945, -0.33631103,  0.80275304]),
  'activation': 'relu'},
 {'name': 'layer-2',
  'weights': array([[ 0.59679054],
         [-0.80576963],
         [ 0.08172214],
         [-0.04323667]]),
  'biases': array([2.17619008]),
  'activation': 'sigmoid'}]

[1 0 1 1 1 1 1 1 0 1] 1
[1 1 1 1 1 1 1 1 0 1] 0


In [9]:
model.forward(temp)

array([[0.88995978],
       [0.89793558]])

### K-Fold Cross Validation

In [ ]:
def k_fold_cross_validation(model,X:np.ndarray, y:np.ndarray, k_folds:int = 4, epochs_per_fold:int = 25):
        fold_size = len(X) // k_folds
        accuracies_fold = []
        accuracies=[]
        losses = []
        for i in range(k_folds):
            start, end = i * fold_size, (i + 1) * fold_size
            X_test_fold, y_test_fold = X[start:end], y[start:end]
            X_train_fold = np.concatenate([X[:start], X[end:]])
            y_train_fold = np.concatenate([y[:start], y[end:]])
            print(f"Training Fold {i+1}\n")
            accuracy, loss = model.train(X_train_fold, y_train_fold, epochs_per_fold)
            accuracies.extend(accuracy)
            losses.extend(loss)
            print("\n"+10*"----"+"\n")
            predictions = model.predict(X_test_fold)
            accuracies_fold.append(accuracy_metric(predictions, y_test_fold))
        return accuracies_fold

In [ ]:
accs = k_fold_cross_validation(model, x, y, epochs_per_fold=50)

In [ ]:
np.average(accs)

In [ ]:
accs

In [ ]:
predictions = model.predict(x)
accuracy_metric(predictions, y)

In [ ]:
model.layers

In [ ]:
count = 0
for i in range(len(y)):
    if predictions[i]==1:
        count+=1
        # print(x[i], y[i], predictions[i])
count

In [ ]:
count

In [6]:
len(x)

1664

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define the model
model = models.Sequential([
    layers.InputLayer(input_shape=(10,)),          # Input layer with size 10
    layers.Dense(4, activation='relu'),          # Hidden layer with size 4 and linear activation
    layers.Dense(1, activation='sigmoid')           # Output layer with size 1 and sigmoid activation
])

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.0)
# Compile the model
model.compile(optimizer=optimizer,loss='mse', metrics=['accuracy'])

# Display the model summary
model.summary()


2024-01-31 14:15:37.847322: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-31 14:15:37.849795: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-31 14:15:37.884502: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-31 14:15:37.884540: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-31 14:15:37.885533: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 1)                 5         
                                                                 
Total params: 49 (196.00 Byte)
Trainable params: 49 (196.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


2024-01-31 14:15:39.663450: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-31 14:15:39.663830: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [25]:
model.fit(x, y, epochs=30, batch_size=16)

Epoch 1/30
104/104 [==============================] - 0s 1ms/step - loss: 0.1518 - accuracy: 0.8948
Epoch 2/30
104/104 [==============================] - 0s 899us/step - loss: 0.1507 - accuracy: 0.8948
Epoch 3/30
104/104 [==============================] - 0s 959us/step - loss: 0.1494 - accuracy: 0.8942
Epoch 4/30
104/104 [==============================] - 0s 903us/step - loss: 0.1483 - accuracy: 0.8948
Epoch 5/30
104/104 [==============================] - 0s 851us/step - loss: 0.1472 - accuracy: 0.8936
Epoch 6/30
104/104 [==============================] - 0s 954us/step - loss: 0.1461 - accuracy: 0.8936
Epoch 7/30
104/104 [==============================] - 0s 918us/step - loss: 0.1450 - accuracy: 0.8942
Epoch 8/30
104/104 [==============================] - 0s 914us/step - loss: 0.1439 - accuracy: 0.8942
Epoch 9/30
104/104 [==============================] - 0s 908us/step - loss: 0.1428 - accuracy: 0.8942
Epoch 10/30
104/104 [==============================] - 0s 889us/step - loss: 0.1417 

In [ ]:
x

In [ ]:
y

In [ ]:
def is_palindrome(arr):
    if np.array_equal(arr, np.flip(arr)):
        return 1
    else:
        return 0

In [ ]:
y_pred = []
for inp in x:
    y_pred.append(is_palindrome(inp))

count = 0
for i in range(len(y)):
    if not y_pred[i]==y[i]:
        count+=1

In [ ]:
count