In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from faker import Faker
import random
np.random.seed()

In [53]:
x = []
palindromes = []
for i in range(1024):
    binary_string = format(i, '010b')
    x.append(binary_string)
    if binary_string == binary_string[::-1]:
        palindromes.append(binary_string)
        
x = np.array(x)
palindromes = np.array(palindromes)

In [54]:
for i in range(5):
    x = np.concatenate((x, palindromes))
print(len(x))

1184


In [55]:
y = []
for binary_string in x:
    y.append(binary_string == binary_string[::-1])
y = np.array(y)
permutation_index = np.random.permutation(len(x))
x = x[permutation_index]
y = y[permutation_index]

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-1 * x))

def relu(x):
    return np.maximum(0, x)

In [7]:
a = np.array([1, 2, -3])
b = np.array([2, 3, 4])
a*b

array([  2,   6, -12])

In [81]:
LEARNING_RATE = 1e-3
NUM_EPOCHS = 10000

input_size = 10
hidden_layer_size = 4
output_size = 1

weights_ih = np.random.rand(input_size, hidden_layer_size)
weights_ho = np.random.rand(hidden_layer_size, output_size)

In [82]:
LEARNING_RATE = 1e-1
for epoch in range(NUM_EPOCHS):
    tot_loss = 0
    for i, s in enumerate(x):
        inp = np.reshape(np.array([int(char) for char in s]), (1, input_size))
        hlayer_logits = np.dot(inp, weights_ih)
        hlayer_output = sigmoid(hlayer_logits)

        final_logits = np.dot(hlayer_output, weights_ho)
        final_output = sigmoid(final_logits)

        tot_loss += abs(final_output - y[i])

        output_delta = (y[i] - final_output) * final_output * (1 - final_output)

        weights_ho += LEARNING_RATE * hlayer_output.T.dot(output_delta)
        weights_ih += LEARNING_RATE * inp.T.dot(output_delta.dot(weights_ho.T) * hlayer_output * (1 - hlayer_output))

    if epoch % 100 == 0:
        print(f'Epoch {epoch} : loss {tot_loss}')

Epoch 0 : loss [[350.69293608]]
Epoch 100 : loss [[299.4903219]]
Epoch 200 : loss [[135.02385372]]
Epoch 300 : loss [[89.33586007]]
Epoch 400 : loss [[72.28477052]]
Epoch 500 : loss [[63.76324349]]
Epoch 600 : loss [[51.21375084]]
Epoch 700 : loss [[42.90495088]]
Epoch 800 : loss [[37.17295526]]
Epoch 900 : loss [[33.01231996]]
Epoch 1000 : loss [[29.85090628]]
Epoch 1100 : loss [[27.35865591]]
Epoch 1200 : loss [[25.1734282]]
Epoch 1300 : loss [[21.63451688]]
Epoch 1400 : loss [[20.43884781]]
Epoch 1500 : loss [[19.54680717]]
Epoch 1600 : loss [[18.74940425]]
Epoch 1700 : loss [[18.02193883]]
Epoch 1800 : loss [[17.35287261]]
Epoch 1900 : loss [[16.7339093]]
Epoch 2000 : loss [[16.15857984]]
Epoch 2100 : loss [[15.62164798]]
Epoch 2200 : loss [[15.1187365]]
Epoch 2300 : loss [[14.64607498]]
Epoch 2400 : loss [[14.20033851]]
Epoch 2500 : loss [[13.77858456]]
Epoch 2600 : loss [[13.37828262]]
Epoch 2700 : loss [[12.99699084]]
Epoch 2800 : loss [[12.62988553]]
Epoch 2900 : loss [[12.2670

In [83]:
count = 0
pal = 0
nonpal = 0
for i, data in enumerate(x):
    inp = np.reshape(np.array([int(char) for char in data]), (1, input_size))
    out = sigmoid(np.dot(sigmoid(np.dot(inp, weights_ih)), weights_ho))
    if out > 0.5 and y[i] == 0:
        nonpal += 1
        count += 1
    if out <= 0.5 and y[i] == 1:
        pal += 1
        count += 1
print(f'Total wrong predicitons: {count}')
print(f'Number of palindromes predicted as non palindromes: {pal}')
print(f'Number of palindromes non predicted as palindromes: {nonpal}')

Total wrong predicitons: 0
Number of palindromes predicted as non palindromes: 0
Number of palindromes non predicted as palindromes: 0


In [84]:
x_test1 = '1000110001'
x_test2 = '1100110000'
def test(x):
    inp = np.reshape(np.array([int(char) for char in x]), (1, input_size))
    return sigmoid(np.dot(sigmoid(np.dot(inp, weights_ih)), weights_ho))

print(test(x_test1))
print(test(x_test2))

[[0.99983459]]
[[3.25529473e-09]]


In [50]:
# np.save('weights_ih.npy', weights_ih)
# np.save('weights_ho.npy', weights_ho)

In [ ]:
# weights_ih = np.load('/Users/utsavmdesai/Documents/Utsav/SEM 8/CS 772/Assignments/assign1-palindrome/weights_ih.npy')
# weights_ho = np.load('/Users/utsavmdesai/Documents/Utsav/SEM 8/CS 772/Assignments/assign1-palindrome/weights_ho.npy')

In [85]:
weights_ho

array([[ 29.52616281],
       [-17.98447369],
       [ 29.44768643],
       [-35.3861514 ]])

In [86]:
weights_ih

array([[ -9.24782865,   1.35153133,   9.98111405,   0.03075372],
       [ -4.304942  ,  -2.42478086,   5.02954046,   7.35538849],
       [  6.86795366,   1.09115832,  -6.18489002,   0.14353161],
       [-24.95550334,   1.08248183,  25.85099723,   0.10903376],
       [-12.3281825 ,   1.10220228,  13.1483093 ,   0.12144731],
       [ 13.04143585,   1.10960998, -12.42752292,   0.12517852],
       [ 25.64254456,   1.08344555, -25.16144267,   0.11997235],
       [ -6.13460765,   1.09091388,   6.92799378,   0.13539465],
       [  4.98673407,  -2.4219316 ,  -4.33870904,   7.37191884],
       [  9.90112064,   1.35089313,  -9.32615158,   0.03972586]])